#!/bin/bash

echo "🔑 SUPABASE SERVICE ROLE KEY SETUP"
echo "=================================="
echo ""
echo "The research scanner needs the Supabase SERVICE ROLE KEY to write to the database."
echo ""
echo "📋 STEPS TO GET THE KEY:"
echo ""
echo "1. Go to your Supabase project dashboard:"
echo "   https://app.supabase.com/project/jgivzyszbpyuvqfmldin/settings/api"
echo ""
echo "2. Copy the 'service_role' key (NOT the anon key)"
echo "   - Look for the key that starts with 'eyJ...' under 'service_role'"
echo "   - This key has admin permissions and can write to your database"
echo ""
echo "3. Add it to Vercel environment variables:"
echo "   Run: vercel env add SUPABASE_SERVICE_ROLE_KEY production"
echo "   Paste the service_role key when prompted"
echo ""
echo "4. Also add to preview and development:"
echo "   vercel env add SUPABASE_SERVICE_ROLE_KEY preview"
echo "   vercel env add SUPABASE_SERVICE_ROLE_KEY development"
echo ""
echo "5. Redeploy (or wait for automatic deployment):"
echo "   git commit --allow-empty -m \"Trigger redeploy for service key\""
echo "   git push origin main"
echo ""
echo "🎯 AFTER ADDING THE KEY:"
echo "- Manual scan will work immediately"
echo "- Daily scans will run automatically"
echo "- Research will be saved to your database"
echo ""
echo "Need the key? Get it here:"
echo "https://app.supabase.com/project/jgivzyszbpyuvqfmldin/settings/api"